# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u4f5c\u8005', 'verbose_name_plural': '\u6587\u7ae0'},
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='\u6b63\u6587'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='\u6807\u9898'),
        ),
    ]
